# Generated by Django 3.0.6 on 2020-05-22 04:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.TextField()),
                ('postimage', models.ImageField(blank=True, upload_to=blog.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photos', to='blog.Photo'),
        ),
    ]
